customer = "XXXX"
owner = "XXXX"

[[account_groups]]
name = "XXXX"
account_ids = ["XXXX"]

[[zone_groups]]
name = "XXXX"
account_id = "XXXX"
zone_ids = ["XXXX"]

[configurations.account_groups.XXXX.account_level]
subscriptions = [
    "advanced_cert_manager_account",
    "advanced_ddos_protection_ent",
    "load_balancing_ent",
    "r2_ent",
    "teams_ent",
    "waf_advanced_accfeat",
    "workers_paid_ent",
]
entitlements = []

[configurations.zone_groups.XXXX.zone_level]
subscriptions = [
    "advanced_cert_manager_free",
    "api_shield_zone",
    "bot_zone_ent",
    "page_shield_ent",
    "cf_ent_app_sec_adv",
    "waiting_rooms_adv",
]
entitlements = []
zone_kvs = []
cdn_rules = []
